### ISSUE TITLE
Enhancement - Add Upvote/downvote

### ISSUE THREAD

**Issue by matthieuEv** [LouvAndTech/quote-bot#4]
It could be intresting to add an upvote/downvote system where everyone could react to the citation using 👍 or 👎 .

Then, we could have a command to show the best rated quote from the week/month/year/all time. This could also be set up as an automatic msg every 1st of the month.

There would be some parameter when you first install the bot to choose if you want the upvote/downvote system, to setup the automatic msg for the best Quote, etc...

**Comment by LouvAndTech** [comment]
Don't forget that I don't save anything on the server side, which mean that in order to allow settings or an automation system I would need to save parameters in the server itself. 
This would be possible _(Using a channel/msg to save the parameters for example)_, but that would be prone to error and probably not practical for everybody.

If you have an Idea of how to do that, or a feature of discord that I don't know about, please let me know.
